[Fix] 16進カラーをTextComponentに適応できないバグを修正
ucchyocean/LunaChat pull request #211
Opened 2020-09-14 20:45 UTC by LazyGon

`new TextComponent(String str)` は引数を解析せずそのまま格納するだけなので、プレイヤーに送信するときも§のまま送信されます。
つまり、例えば `#123456` は `§x§1§2§3§4§5§6` に変換され、これはクライアント側で `§6` と解釈されます。
それに対して`TextComponent.fromLegacyText(String str)` は、ちゃんと文字列に含まれる§を解析して適当な色を`setColor`してくれます。
なので、こちらに置き換えました。

ちなみに、`§x§1§1§1§1§1§1`  のような表現がクライアント側でうまく変換されないのは、この表現がvanillaのものではなくSpigot由来のためだそうで。
vanillaではjsonメッセージ以外では16進カラーに対応していないらしいです。

2020-09-14 21:30 UTC, LazyGon commented
あと、コンソールに表示されるメッセージも地味に色が適応されませんが、これはそう簡単には治せなさそうです。
そもそも16進カラーに対応してるターミナルがそんなになさそうですし。
苦肉の策として、もういっそ16進カラーは全部そのまま表示すれば、統一感がでそうな気はします。

現状だと直した問題と全く同様に`§x`だけ残って一番最後の `§` の色が適応されてるので、やっぱりバグっぽく見えます。
https://gyazo.com/9b2755bcb64d6ad6ba1f80b8f21cc8b4

2020-09-15 00:55 UTC, ucchyocean requested changes
PRありがとうございます。
なぜか、全行差分になっちゃっています。
たぶん、改行コードが変わってしまっているためだと思います。
直すことは可能ですか？

2020-09-15 04:53 UTC, LazyGon commented
な、直せない...。

2020-09-15 05:06 UTC, LazyGon commented
CRLFにしたら上手く行きました。

2020-09-15 12:06 UTC, LazyGon commented
最初に書くべきことでしたが、このバグが具体的に影響を及ぼすのを再現するなら
* 発言先チャンネルフォーマットに `%username` を含める
* `Essentials` を導入し、nickコマンドで `getDisplayName()` の結果に16進数カラーを入れる
* 発言する

という手順でできると思います。
明らかに置換された `%username` の16進数カラーが、そのカラーの一番最後の `§` の色になってしまうのでわかりやすいかと。

私はBungee環境で実験しましたが、コード的にはSpigotのみでも同じことが起きそうな気がしますね。

2020-09-15 15:25 UTC, ucchyocean approved these changes

2020-09-15 15:26 UTC, merged

2020-09-15 15:27 UTC, ucchyocean commented
ご対応ありがとうございます。
問題の現象についても、動作検証して再現できて、PRの内容で修正できることも確認できたので、ソースコードをマージさせてもらいます。